services:
  postgres:
    image: postgres:16
    container_name: chess_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chess
    ports:
      - "5432:5432"
    volumes:
      - chess_pgdata:/var/lib/postgresql/data
volumes:
  chess_pgdata: